apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.engine.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.engine.name }}
    app.kubernetes.io/instance: {{ .Values.releaseName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: engine
    app.kubernetes.io/part-of: grapharna-web
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.engine.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.engine.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.engine.name }}
    spec:
      strategy:
        type: Recreate
        
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000

      containers:
        - name: {{ .Values.engine.name }}
          image: {{ .Values.engine.image }}
          imagePullPolicy: {{ .Values.engine.pullPolicy }}

          ports:
            - containerPort: {{ .Values.engine.port }}

          volumeMounts:
            - name: shared-volume
              mountPath: /shared
            - name: tmp-dir
              mountPath: /tmp
            - name: data-volume
              mountPath: /app/data
            - name: cache-volume
              mountPath: /.cache

          livenessProbe:
            httpGet:
              path: {{ .Values.engine.livenessPath }}
              port: {{ .Values.engine.port }}
            initialDelaySeconds: 30
            periodSeconds: 180
            failureThreshold: 300
            timeoutSeconds: 10

          readinessProbe:
            httpGet:
              path: {{ .Values.engine.readinessPath }}
              port: {{ .Values.engine.port }}
            initialDelaySeconds: 5  
            periodSeconds: 5

          resources:
            requests:
              cpu: {{ .Values.engine.resources.requests.cpu }}
              memory: {{ .Values.engine.resources.requests.memory }}
            limits:
              cpu: {{ .Values.engine.resources.limit.cpu }}
              memory: {{ .Values.engine.resources.limit.memory }}

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL

      volumes: 
        - name: shared-volume
          persistentVolumeClaim:
            claimName: {{ .Values.backend.pvc }}
        - name: tmp-dir
          emptyDir: {}
        - name: data-volume
          emptyDir: {}
        - name: cache-volume
          emptyDir: {}
