apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.engine.name }}-svc
  labels:
    app.kubernetes.io/name: {{ .Values.engine.name }}
    app.kubernetes.io/instance: {{ .Values.releaseName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: engine
    app.kubernetes.io/part-of: grapharna-web
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.engine.name }}
  ports:
  - port: 8080
    targetPort: {{ .Values.engine.port }}
