services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: grapha_front
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - frontend
      - backend

  db:
    image: postgres:15
    container_name: grapha_pg
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: grapha_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - shared_volume:/shared
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/healthcheck/"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend

  grapharna-engine:
    # build:
    #   context: ./GraphaRNA
    #   dockerfile: Dockerfile
    image: grapharnaweb/grapharna-web:grapharna-engine
    container_name: grapha_engine
    volumes:
      - shared_volume:/shared
    ports:
      - "8080:8080"
    # deploy: # it should be uncommented if you wish to run engine on GPU
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: grapha_rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_CONSUMER_TIMEOUT=129600000
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "guest:guest", "http://localhost:15672/api/healthchecks/node"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend

  celery-grapharna:
    build:
      context: ./backend
    container_name: grapha_celery_grapharna
    command: celery -A GraphaRNA worker -Q grapharna --concurrency=1 --loglevel=info
    volumes:
      - shared_volume:/shared
      - ./backend:/app
    env_file:
     - ./backend/.env
    depends_on:
      - backend
      - rabbitmq
    networks:
      - backend
    
  celery-maintenance:
    build:
      context: ./backend
    container_name: grapha_celery_maintenance
    command: celery -A GraphaRNA worker -Q maintenance --loglevel=info
    volumes:
      - shared_volume:/shared
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - rabbitmq
    networks:
      - backend
  
  celery-email:
    build:
      context: ./backend
    container_name: grapha_celery_email
    command: celery -A GraphaRNA worker -Q email --loglevel=info
    volumes:
      - shared_volume:/shared
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - rabbitmq
    networks:
      - backend
    
  celery-beat:
    build:
      context: ./backend
    container_name: grapha_celery_beat
    command: celery -A GraphaRNA beat --loglevel=info
    volumes:
      - shared_volume:/shared
      - ./backend:/app
    env_file:
     - ./backend/.env
    depends_on:
      - backend
      - rabbitmq
    networks:
      - backend
      
volumes:
  postgres_data:
  shared_volume:
  rabbitmq_data:

networks:
  backend:
  frontend:
