apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-svc
  labels:
    app.kubernetes.io/name: {{ .Values.postgres.name }}
    app.kubernetes.io/instance: {{ .Values.releaseName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: grapharna-web
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.postgres.name }}
  ports:
  - port: 5432
    targetPort: {{ .Values.postgres.port }}
