{{- if .Values.frontend.ingressEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.frontend.name }}-ingress
  labels:
    app.kubernetes.io/name: {{ .Values.frontend.name }}
    app.kubernetes.io/instance: {{ .Values.releaseName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: grapharna-web
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: public
  tls:
  - hosts:
    - grapharna.cs.put.poznan.pl
    secretName: grapharna-tls-secret-prod-final
  
  rules:
  - host: grapharna.cs.put.poznan.pl
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.frontend.name }}-svc
            port:
              number: 80
{{- end }}
