apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-svc
  labels:
    app.kubernetes.io/name: {{ .Values.frontend.name }}
    app.kubernetes.io/instance: {{ .Values.releaseName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: grapharna-web
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.frontend.name }}
  ports:
  - port: 80
    targetPort: {{ .Values.frontend.port }}
