apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: grapharna
data:
  DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "127.0.0.1,localhost,backend-svc,150.254.30.175"

  DATABASE_ENGINE: "django.db.backends.postgresql"
  DATABASE_NAME: "dockerdjango"
  DATABASE_HOST: "db-svc"
  DATABASE_PORT: "5432"

  JOB_EXPIRATION_WEEKS: "2"
  MODEL_NAME: "model_800.h5"
  MODEL_EPOCHS: "800"
  UUID_HASH_LENGTH: "5"
  
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "465"
  TEMPLATE_PATH_JOB_CREATED: "email_templates/template_job_created.html"
  TEMPLATE_PATH_JOB_FINISHED: "email_templates/template_job_finished.html"
  TEMPLATE_PATH_JOB_NEAR_EXPIRATION: "email_templates/template_job_near_expiration.html"
  EMAIL_TITLE_JOB_CREATED: "Your job has been created!"
  EMAIL_TITLE_JOB_FINISHED: "Your job is finished!"
  EMAIL_TITLE_JOB_NEAR_EXPIRATION: "Your job is about to expire!"

  ENGINE_URL: "http://grapharna-engine-svc:8080/run"

  RESULT_BASE_URL: "http://150.254.30.175/api/getResults/" 
