apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-svc
  labels:
    app.kubernetes.io/name: {{ .Values.backend.name }}
    app.kubernetes.io/instance: {{ .Values.releaseName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: grapharna-web
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.backend.name }}
  ports:
  - port: 8000
    targetPort: {{ .Values.backend.port }}
