apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.name }}-svc
  labels:
    app.kubernetes.io/name: {{ .Values.rabbitmq.name }}
    app.kubernetes.io/instance: {{ .Values.releaseName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/part-of: grapharna-web
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.rabbitmq.name }}
  ports:
    - name: amqp
      port: 5672
      targetPort: {{ .Values.rabbitmq.port }}
    - name: management
      port: 15672
      targetPort: {{ .Values.rabbitmq.uiPort }}
