name: Django CI

on:
  push:
    branches:
      - '**'
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: dockerdjango
          POSTGRES_USER: dbuser
          POSTGRES_PASSWORD: dbpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_SECRET_KEY: test
      DEBUG: True
      DJANGO_ALLOWED_HOSTS: 127.0.0.1,localhost
      DATABASE_ENGINE: django.db.backends.postgresql
      DATABASE_NAME: dockerdjango
      DATABASE_USERNAME: dbuser
      DATABASE_PASSWORD: dbpassword
      DATABASE_HOST: localhost  # w serwerze db - tu musi byÄ‡ lokalny serwis
      DATABASE_PORT: 5432
      DJANGO_SETTINGS_MODULE: GraphaRNA.settings

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m venv backend/venv
          source backend/venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            nc -z 127.0.0.1 5432 && echo "Postgres is up" && break
            echo "Waiting for postgres..."
            sleep 3
          done

      - name: Run Migrations
        run: |
          source backend/venv/bin/activate
          python backend/manage.py migrate --noinput
      
      - name: Run api tests (PostRnaDataTests)
        run: |
          source backend/venv/bin/activate
          python backend/manage.py test api.test_api.PostRnaDataTests

      - name: Run api tests (GetResultsTests)
        run: |
          source backend/venv/bin/activate
          python backend/manage.py test api.test_api.GetResultsTests
          
      - name: Run api tests (SuggestSeedAndJobNameTests)
        run: |
          source backend/venv/bin/activate
          python backend/manage.py test api.test_api.SuggestSeedAndJobNameTests

      - name: Run api tests (PostRnaValidationTests)
        run: |
          source backend/venv/bin/activate
          python backend/manage.py test api.test_api.PostRnaValidationTests

      - name: Run api tests (DownloadZipFileTests)
        run: |
          source backend/venv/bin/activate
          python backend/manage.py test api.test_api.DownloadZipFileTests

      - name: Run api tests (INF)
        run: |
          source backend/venv/bin/activate
          python backend/manage.py test api.test_api.INF

      - name: Code audit
        run: |
          source backend/venv/bin/activate
          mypy backend/ --config-file backend/mypy.ini
          ruff check backend/
