name: Django CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: dockerdjango
          POSTGRES_USER: dbuser
          POSTGRES_PASSWORD: dbpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_SECRET_KEY: test
      DEBUG: True
      DJANGO_ALLOWED_HOSTS: 127.0.0.1,localhost
      DATABASE_ENGINE: django.db.backends.postgresql
      DATABASE_NAME: dockerdjango
      DATABASE_USERNAME: dbuser
      DATABASE_PASSWORD: dbpassword
      DATABASE_HOST: localhost  # w serwerze db - tu musi byÄ‡ lokalny serwis
      DATABASE_PORT: 5432
      DJANGO_SETTINGS_MODULE: GraphaRNA.settings

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m venv backend/venv
          source backend/venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Install R
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base r-base-dev

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            nc -z 127.0.0.1 5432 && echo "Postgres is up" && break
            echo "Waiting for postgres..."
            sleep 3
          done

      - name: Run tests
        run: |
          source backend/venv/bin/activate
          python backend/manage.py migrate --noinput
          python backend/manage.py test
          python backend/manage.py test api.tests_api.PostRnaDataTests

      - name: Code audit
        run: |
          source backend/venv/bin/activate
          mypy backend/ --config-file backend/mypy_ci.ini
          ruff check backend/
