name: Build Next.js site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node (npm) for the frontend, this should be run outside of the frontend directory
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      # Restore cache for frontend dependencies
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-nextjs-${{ hashFiles('frontend/package-lock.json') }}-${{ hashFiles('frontend/**.[jt]s', 'frontend/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('frontend/package-lock.json') }}-

      # Install dependencies inside the frontend folder
      - name: Install dependencies
        run: npm install
        working-directory: frontend

      # Build with Next.js inside the frontend folder
      - name: Build with Next.js
        run: npm run build
        working-directory: frontend

      # Optional: Run tests or linting if you want to add checks
      - name: Run Next.js tests
        run: npm test
        working-directory: frontend

      - name: Lint Next.js code
        run: npm run lint
        working-directory: frontend
